# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Base properties
    minecraftVersion=1.7.10
    forgeVersion=10.13.4.1614
    channel=stable
    mappingsVersion=12
    remoteMappings=https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
    enableModernJavaSyntax=jvmDowngrader
    downgradeTargetVersion=8
    enableGenericInjection=true
    usesMixins=true
    mixinsPackage=mixin
    generateGradleTokenClass=com.rubenverg.moldraw.Tags

# Mod Properties
    customArchiveBaseName=gtmoldraw
    modId=moldraw
    modVersion=3.3.2-any-2.9-patch
    modName=GregTech Molecule Drawings
    modGroup=com.rubenverg.moldraw
    useModGroupForPublishing=true

# Dependencies
    neiVersion=2.8.130-GTNH
    gtVersion=5.09.54.133
    chromaticVersion=1.0.17-GTNH
    chromaticCompatVersion=1.0.23-GTNH
